name = "Gianpaulo"
print(len(name))
print(name.upper().isupper(), name.upper())
print(name.lower().islower(), name.lower())
print(name[0], name[1], name[2], name[3], name[4], name[5], name[6], name[7], name[8])
print(name.endswith('o'), name.startswith('G'))
print(name.split().reverse())
print(name.find("p"))
print(name.isdigit())
print(name.isalpha())
print(name.count("a"))
print(name.replace("a", "o"))
print(name*3)
